export interface EmojiItem {
  char: string;
  name: string;
}
export const emojis = [
  { char: "😀", name: "Grinning face" },
  { char: "😃", name: "Grinning face with big eyes" },
  { char: "😄", name: "Grinning face with smiling eyes" },
  { char: "😁", name: "Beaming face with smiling eyes" },
  { char: "😆", name: "Grinning squinting face" },
  { char: "😅", name: "Grinning face with sweat" },
  { char: "😂", name: "Face with tears of joy" },
  { char: "🤣", name: "Rolling on the floor laughing" },
  { char: "😊", name: "Smiling face with smiling eyes" },
  { char: "😇", name: "Smiling face with halo" },
  { char: "🙂", name: "Slightly smiling face" },
  { char: "🙃", name: "Upside-down face" },
  { char: "😉", name: "Winking face" },
  { char: "😌", name: "Relieved face" },
  { char: "😍", name: "Smiling face with heart-eyes" },
  { char: "🥰", name: "Smiling face with hearts" },
  { char: "😘", name: "Face blowing a kiss" },
  { char: "😗", name: "Kissing face" },
  { char: "😙", name: "Kissing face with smiling eyes" },
  { char: "😚", name: "Kissing face with closed eyes" },
  { char: "😋", name: "Face savoring food" },
  { char: "😛", name: "Face with tongue" },
  { char: "😝", name: "Squinting face with tongue" },
  { char: "😜", name: "Winking face with tongue" },
  { char: "🤪", name: "Zany face" },
  { char: "🤨", name: "Face with raised eyebrow" },
  { char: "🧐", name: "Face with monocle" },
  { char: "🤓", name: "Nerd face" },
  { char: "😎", name: "Smiling face with sunglasses" },
  { char: "🤩", name: "Star-struck" },
  { char: "🥳", name: "Partying face" },
  { char: "😏", name: "Smirking face" },
  { char: "😒", name: "Unamused face" },
  { char: "😞", name: "Disappointed face" },
  { char: "😔", name: "Pensive face" },
  { char: "😟", name: "Worried face" },
  { char: "😕", name: "Confused face" },
  { char: "🙁", name: "Slightly frowning face" },
  { char: "☹️", name: "Frowning face" },
  { char: "😣", name: "Persevering face" },
  { char: "😖", name: "Confounded face" },
  { char: "😫", name: "Tired face" },
  { char: "😩", name: "Weary face" },
  { char: "🥺", name: "Pleading face" },
  { char: "😢", name: "Crying face" },
  { char: "😭", name: "Loudly crying face" },
  { char: "😤", name: "Face with steam from nose" },
  { char: "😠", name: "Angry face" },
  { char: "😡", name: "Pouting face" },
  { char: "🤬", name: "Face with symbols on mouth" },
  { char: "🤯", name: "Exploding head" },
  { char: "😳", name: "Flushed face" },
  { char: "🥵", name: "Hot face" },
  { char: "🥶", name: "Cold face" },
  { char: "😱", name: "Face screaming in fear" },
  { char: "😨", name: "Fearful face" },
  { char: "😰", name: "Anxious face with sweat" },
  { char: "😥", name: "Sad but relieved face" },
  { char: "😓", name: "Downcast face with sweat" },
  { char: "🤗", name: "Hugging face" },
  { char: "🤔", name: "Thinking face" },
  { char: "🤭", name: "Face with hand over mouth" },
  { char: "🤫", name: "Shushing face" },
  { char: "🤥", name: "Lying face" },
  { char: "😶", name: "Face without mouth" },
  { char: "😐", name: "Neutral face" },
  { char: "😑", name: "Expressionless face" },
  { char: "😬", name: "Grimacing face" },
  { char: "🙄", name: "Face with rolling eyes" },
  { char: "😯", name: "Hushed face" },
  { char: "😦", name: "Frowning face with open mouth" },
  { char: "😧", name: "Anguished face" },
  { char: "😮", name: "Face with open mouth" },
  { char: "😲", name: "Astonished face" },
  { char: "🥱", name: "Yawning face" },
  { char: "😴", name: "Sleeping face" },
  { char: "🤤", name: "Drooling face" },
  { char: "😪", name: "Sleepy face" },
  { char: "😵", name: "Dizzy face" },
  { char: "🤐", name: "Zipper-mouth face" },
  { char: "🥴", name: "Woozy face" },
  { char: "🤢", name: "Nauseated face" },
  { char: "🤮", name: "Face vomiting" },
  { char: "🤧", name: "Sneezing face" },
  { char: "😷", name: "Face with medical mask" },
  { char: "🤒", name: "Face with thermometer" },
  { char: "🤕", name: "Face with head-bandage" },
  { char: "🤑", name: "Money-mouth face" },
  { char: "🤠", name: "Cowboy hat face" },
  { char: "😈", name: "Smiling face with horns" },
  { char: "👿", name: "Angry face with horns" },
  { char: "👹", name: "Ogre" },
  { char: "👺", name: "Goblin" },
  { char: "🤡", name: "Clown face" },
  { char: "💩", name: "Pile of poo" },
  { char: "🤖", name: "Robot" },
  { char: "🎃", name: "Jack-o-lantern" },
  { char: "😺", name: "Grinning cat" },
  { char: "😸", name: "Grinning cat with smiling eyes" },
  { char: "😹", name: "Cat with tears of joy" },
  { char: "😻", name: "Smiling cat with heart-eyes" },
  { char: "😼", name: "Cat with wry smile" },
  { char: "😽", name: "Kissing cat" },
  { char: "🙀", name: "Weary cat" },
  { char: "😿", name: "Crying cat" },
  { char: "😾", name: "Pouting cat" }
];